version: '3.8'

services:
  pytorch-0.4.1:
    build: pytorch-0.4.1
    tty: true
    environment:
      - ENVIRONMENT=beta
    user: ${CURRENT_UID}
    volumes:
      - type: bind
        source: ../
        target: /app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    command: >
      sh -c "cd /app &&
             python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=test_images &&
             python classify.py"
