version: '3.8'

services:
  planercnn:
    build: planercnn
    tty: true
    environment:
      - ENVIRONMENT=beta
    volumes:
      - type: bind
        source: ../
        target: /app
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    command: >
      sh -c "cd /app &&
             sh build_lib.sh &&
             python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=test_images &&
             python classify.py"
